"use strict";
process.env.NODE_ENV = "test";
process.env.PILOT_V2_INVITE_SECRET = "pilot-contract-secret-with-at-least-thirty-two-bytes";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { MemoryDatabaseAdapter } = require("../support/memory-database.js");
const { setDatabaseForTests } = require("../../netlify/functions/_lib/store.js");
const { createInvite } = require("../../netlify/functions/_lib/pilot-v2-access.js");
const database = new MemoryDatabaseAdapter();
setDatabaseForTests(database);
const access = require("../../netlify/functions/pilot-v2-access.js").handler;
const instrument = require("../../netlify/functions/pilot-v2-instrument.js").handler;
const assessment = require("../../netlify/functions/pilot-v2-assessment.js").handler;
const request = (method, token = "", body = null) => ({ httpMethod: method, headers: token ? { authorization: `Pilot ${token}` } : {}, body: body == null ? null : JSON.stringify(body) });
(async () => {
  assert.equal((await access(request("GET"))).statusCode, 401);
  assert.equal((await instrument(request("GET"))).statusCode, 401);
  const token = createInvite({ expiresAt: new Date(Date.now() + 60000), inviteId: "contract-invite" });
  assert.equal((await access(request("GET", token))).statusCode, 200);
  const loaded = await instrument(request("GET", token));
  assert.equal(JSON.parse(loaded.body).instrument.items.length, 49);
  const started = await assessment(request("POST", token, { action: "start" }));
  assert.equal(started.statusCode, 201);
  assert.equal(database.pilotV2Events.length, 0);
  const publicIndex = fs.readFileSync(path.join(__dirname, "../../index.html"), "utf8");
  assert.equal(publicIndex.includes("/pilot-v2"), false);
  const publicApp = fs.readFileSync(path.join(__dirname, "../../app.js"), "utf8");
  assert.equal(publicApp.includes("pilot-v2"), false);
  assert.equal(fs.readFileSync(path.join(__dirname, "../../questions.js"), "utf8").length > 0, true);
  const crypto = require("node:crypto");
  assert.equal(crypto.createHash("sha256").update(fs.readFileSync(path.join(__dirname, "../../questions.js"))).digest("hex"), "ac79aa5e83d6c37234f886f2683fd036ba80862afa5f3b6f3d8b2131f7f22d14");
  const migration = fs.readFileSync(path.join(__dirname, "../../supabase/migrations/20260729090000_add_private_pilot_v2_1_storage.sql"), "utf8");
  assert(migration.includes("jingeehas_pilot.lifecycle_events"));
  assert.equal(migration.includes("analytics_events"), false);
  console.log("pilot V2 access contract tests passed");
})().catch(error => { console.error(error); process.exit(1); });
