"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const app = fs.readFileSync("app.js", "utf8");
const state = fs.readFileSync("netlify/functions/weight-session-state.js", "utf8");
const analytics = fs.readFileSync("netlify/functions/_lib/analytics.js", "utf8");
const collector = fs.readFileSync("netlify/functions/analytics-collect.js", "utf8");
assert(app.includes("Таны өмнөх тест"));
assert(app.includes("Төлбөрөө үргэлжлүүлэх"));
assert(app.includes("Тестээ үргэлжлүүлэх"));
assert(app.includes("Тайлангаа харах"));
assert(app.includes("Өөр төхөөрөмжөөс сэргээх"));
assert(app.includes("resume_entry_shown"));
assert(app.includes("resume_entry_clicked"));
assert(state.includes("authenticateSession(database, event, false)"));
assert(app.includes("function landingCta()"));
assert(app.includes("landingCtaAttributes(cta)"));
assert(!app.includes('href="/assessment/start" data-route data-primary-cta>${primary}'));
assert(app.includes("metadata?.stateCategory"));
assert(analytics.includes("safeBrowserMetadata"));
assert(analytics.includes("metadata.stateCategory || \"unknown\""));
assert(collector.includes("safeBrowserMetadata(body.eventName, body.metadata || {})"));
assert(!app.includes("assessmentId</h2>"));
assert(!app.includes("paymentId</h2>"));
console.log("customer resume entry tests passed");
