const assert = require("assert");
const fs = require("fs");
const app = require("../app.js");
const I = app._internal;
const invoice = { qrImage: "abc", senderInvoiceNo: "INV-TEST-001", urls: [{ name: "Тест банк", link: "bank://pay" }] };
const text = html => String(html).replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
const setPayment = (qpayPayment, view = "oneTimeStart") => I.setTestState({ view, packageType: "one-time", oneTimePaid: qpayPayment.status === "paid", contactCapture: { name: "", phone: "99119911", email: "", saved: true, message: "", copyStatus: "" }, qpayPayment });

assert.notStrictEqual(text(I.renderNoAccountPaymentIntro("pre_test")), text(I.renderNoAccountPaymentIntro("report")));
assert(text(I.renderNoAccountPaymentIntro("pre_test")).includes("Төлбөр баталгаажмагц тест нээгдэнэ."));
assert(text(I.renderNoAccountPaymentIntro("report")).includes("Тестийг дахин бөглөх шаардлагагүй."));
setPayment({ status: "idle", message: "", invoice: null, checkAttemptCount: 0 });
assert(text(I.renderWeightQpayPaymentBox({ context: "pre_test" })).includes("9,900₮-ийн QPay төлбөрийн QR код үүсгэх"));
setPayment({ status: "creating", message: I.qpayStatusMessage("creating"), invoice: null, checkAttemptCount: 0 });
assert(text(I.renderWeightQpayPaymentBox({ context: "pre_test" })).includes("QR код үүсгэж байна…"));
setPayment({ status: "pending", message: I.qpayStatusMessage("pending"), invoice, checkAttemptCount: 0 });
assert(text(I.renderWeightQpayPaymentBox({ context: "pre_test" })).includes("Төлбөр шалгах"));
assert(!text(I.renderWeightQpayPaymentBox({ context: "pre_test" })).includes("Дахин шалгах"));
setPayment({ status: "pending", message: I.qpayStatusMessage("pending"), invoice, checkAttemptCount: 1 });
assert(text(I.renderWeightQpayPaymentBox({ context: "pre_test" })).includes("Дахин шалгах"));
setPayment({ status: "checking", message: I.qpayStatusMessage("checking"), invoice, checkAttemptCount: 1 });
assert(text(I.renderWeightQpayPaymentBox({ context: "pre_test" })).includes("Төлбөр шалгаж байна…"));
setPayment({ status: "error", errorKind: "create", message: I.qpayStatusMessage("create_error"), invoice: null, checkAttemptCount: 0 });
assert(text(I.renderWeightQpayPaymentBox({ context: "pre_test" })).includes("QR код дахин үүсгэх"));
assert(!I.renderWeightQpayPaymentBox({ context: "pre_test" }).includes("checkWeightQpayPayment"));
setPayment({ status: "error", errorKind: "check", message: I.qpayStatusMessage("check_error"), invoice, checkAttemptCount: 1 });
const checkError = I.renderWeightQpayPaymentBox({ context: "pre_test" });
assert(text(checkError).includes("Төлбөр дахин шалгах"));
assert(checkError.includes("INV-TEST-001") && checkError.includes("qpay-qr"));
setPayment({ status: "paid", message: I.qpayStatusMessage("paid", "pre_test"), invoice, checkAttemptCount: 1 });
const paidPre = I.renderWeightQpayPaymentBox({ context: "pre_test" });
assert(text(paidPre).includes("Тест эхлүүлэх"));
assert(!paidPre.includes("qpay-payment-surfaces") && !paidPre.includes("checkWeightQpayPayment"));
setPayment({ status: "paid", message: I.qpayStatusMessage("paid", "report"), invoice, checkAttemptCount: 1 }, "report");
const paidReport = I.renderWeightQpayPaymentBox({ context: "report" });
assert(text(paidReport).includes("Бүрэн тайлангаа харах"));
assert(!paidReport.includes("qpay-payment-surfaces"));
const source = fs.readFileSync("app.js", "utf8");
for (const invariant of ["9,900₮", "9900", "WEIGHT_TEST_ONE_TIME", "/.netlify/functions/qpay-create-invoice", "/.netlify/functions/qpay-check-payment"]) assert(source.includes(invariant));
for (const key of ["coachId", "coachClientId", "coachInvite", "coachDiscountConsent", "coachOneTime"]) assert(source.includes(key));
console.log("one-time payment copy and state tests passed");
