"use strict";
process.env.NODE_ENV = "test";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { instrument, registry, scorePilot, evaluateResponseQuality, buildPilotReport, ORDER } = require("../netlify/functions/_lib/pilot-v2-engine.js");
const scales = require("../pilot-v2/scale-registry.js");
const fixtures = require("./fixtures/pilot-v2-synthetic.js");
const { createInvite, verifyInvite } = require("../netlify/functions/_lib/pilot-v2-access.js");

assert.equal(instrument.items.length, 49);
assert.equal(instrument.items.filter(item => item.pilotRole === "scored_core_candidate").length, 48);
const heldText = fs.readFileSync(path.join(__dirname, "../docs/psychometrics/candidate-bank-v2-1/HELD_ITEMS_V2_1.csv"), "utf8");
for (const item of instrument.items) assert.equal(heldText.split(/\r?\n/).slice(1).some(line => line.startsWith(`${item.itemKey},`)), false);
assert.deepEqual(new Set(instrument.items.filter(item => item.pilotRole === "scored_core_candidate").map(item => item.construct)), new Set(ORDER));
for (const scaleId of Object.keys(registry)) for (let index = 0; index < 5; index += 1) assert.equal(scales.score(scaleId, String(index)), index);
assert.equal(scales.score("frequency_14d_opportunity_0_4_na", "NA"), null);
for (const item of instrument.items.filter(item => item.pilotRole === "scored_core_candidate")) assert.match(item.scoringDirection, /^higher_(barrier|capability)$/);
const engineText = fs.readFileSync(path.join(__dirname, "../netlify/functions/_lib/pilot-v2-engine.js"), "utf8");
for (const forbidden of ["+1", "+2", "+3", "mandatory anchor", "regex", "threshold"]) assert.equal(engineText.toLowerCase().includes(forbidden), false);
const emotionalItems = instrument.items.filter(item => item.construct === "emotional_eating");
const partial = Object.fromEntries(emotionalItems.slice(0, 5).map(item => [item.itemKey, "4"]));
assert.equal(scorePilot(partial).constructs.emotional_eating.dataStatus, "partial_scorable");
assert.equal(scorePilot(Object.fromEntries(emotionalItems.slice(0, 4).map(item => [item.itemKey, "4"]))).constructs.emotional_eating.dataStatus, "insufficient_data");
const rebound = instrument.items.filter(item => item.construct === "restrictive_rebound");
assert.equal(scorePilot(Object.fromEntries(rebound.slice(0, 3).map(item => [item.itemKey, "4"]))).constructs.restrictive_rebound.dataStatus, "insufficient_data");
assert.equal(scorePilot(Object.fromEntries(rebound.map(item => [item.itemKey, "4"]))).constructs.restrictive_rebound.dataStatus, "complete");
assert.equal(scorePilot(fixtures.allHighEndorsement).constructs.emotional_eating.transformedScore, 100);
const base = scorePilot(fixtures.mixedProfile);
const qualityKey = instrument.items.find(item => item.pilotRole === "non_scored_research_quality").itemKey;
assert.deepEqual(scorePilot({ ...fixtures.mixedProfile, [qualityKey]: "4" }).constructs, base.constructs);
assert.equal(evaluateResponseQuality(fixtures.straightLineQualityFlag).straightLinePattern, true);
assert.equal(evaluateResponseQuality(fixtures.straightLineQualityFlag).affectsProfileScores, false);
const report = buildPilotReport({ answers: fixtures.mixedProfile });
assert.equal(report.interactions.enabled, false);
assert.deepEqual(buildPilotReport({ answers: fixtures.mixedProfile, context: { injury: true } }).sections.profile.constructs, report.sections.profile.constructs);
assert.deepEqual(buildPilotReport({ answers: fixtures.mixedProfile, safety: { urgent: true } }).sections.profile.constructs, report.sections.profile.constructs);
const customer = JSON.stringify(report).toLowerCase();
for (const term of ["risk level", "percentile", "clinical cut-off", '"high"', '"medium"', '"low"']) assert.equal(customer.includes(term), false);
for (const item of instrument.items) assert.equal(customer.includes(item.itemText.toLowerCase()), false);
assert.equal(report.sections.provenance.instrumentVersion, "jingeehas-ai-pilot-v2.1");
assert.equal(report.sections.provenance.scoringVersion, "jingeehas-ai-pilot-scoring-v2.1-equal-weight");
assert.equal(report.sections.provenance.reportVersion, "jingeehas-ai-pilot-report-v2.1");
const raw = fs.readFileSync(path.join(__dirname, "../docs/psychometrics/candidate-bank-v2-1/PILOT_CANDIDATE_BANK_V2_1.csv"));
assert.equal(instrument.itemBankSha256, crypto.createHash("sha256").update(raw).digest("hex"));
const env = { PILOT_V2_INVITE_SECRET: "software-test-secret-at-least-thirty-two-bytes" };
const token = createInvite({ expiresAt: new Date(Date.now() + 60000), inviteId: "synthetic-fixture" }, env);
assert.equal(verifyInvite(token, env).jti, "synthetic-fixture");
assert.throws(() => verifyInvite(token, env, new Date(Date.now() + 120000)), error => error.code === "pilot_access_denied");
console.log("pilot-v2.test.js passed");
